service:
 name: antifraud-provider

plugins:
 - 'serverless-plugin-typescript'
 - serverless-offline

provider:
 name: aws
 runtime: nodejs12.x
 
package:
  individually: true

custom:
  funcDir: src/4-framework/functions

functions:
  - ${file(${self:custom.funcDir}/_handlers.yml)}
